learning_log/learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
    path("", include("learning_logs.urls")),
]

handler404 = "learning_log.views.page_not_found_view"
handler500 = "learning_log.views.internal_error_view"

learning_log/learning_logs/urls.py
"""Defines URL patterns for learning_logs"""

from django.urls import path

from . import views

app_name = "learning_logs"
urlpatterns = [
    # Home page
    path("", views.index, name="index"),
    # Page that shows all topics
    path("topics", views.topics, name="topics"),
    # Detail page for a single topic
    path("topics/<int:topic_id>/", views.topic, name="topic"),
    # Page for adding a new topic
    path("new_topic", views.new_topic, name="new_topic"),
    # Page for adding a new entry
    path("new_entry/<int:topic_id>/", views.new_entry, name="new_entry"),
    # Page for editing an entry
    path("edit_entry/<int:entry_id>/", views.edit_entry, name="edit_entry"),
]

learning_log/users/urls.py
"""Defines URL patterns for users"""

from django.urls import path, include

from . import views

app_name = "users"
urlpatterns = [
    # Include default auth urls
    path("", include("django.contrib.auth.urls")),
    # Registration page
    path("register/", views.register, name="register"),
]

learning_log/learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
    """A topic the user is learning about"""

    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    topic_visibility_options = [(False, "Private"), (True, "Public")]
    public = models.BooleanField(
        max_length=10, choices=topic_visibility_options, default=False
    )

    def __str__(self):
        """Return a string representation of the model"""
        return self.text


class Entry(models.Model):
    """Some text in the topic"""

    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "entries"

    def __str__(self):
        """Return a string representation of the model"""
        if len(self.text) > 50:
            str = f"{self.text[:50]}..."
        else:
            str = self.text
        return str

learning_log/users/models.py
from django.db import models

# Create your models here.

learning_log/learning_logs/forms.py
from django import forms

from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ["text", "public"]
        labels = {"text": "", "public": ""}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ["text"]
        labels = {"text": ""}
        widgets = {"text": forms.Textarea(attrs={"cols": 80})}

learning_log/learning_log/views.py
from django.shortcuts import render


def page_not_found_view(request, exception):
    return render(request, "404.html", status=404)


def internal_error_view(request):
    return render(request, "500.html", status=500)

learning_log/learning_logs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.db.models import Q

from .models import Topic, Entry
from .forms import TopicForm, EntryForm


def index(request):
    """Learning log home page"""
    return render(request, "learning_logs/index.html")


def topics(request):
    """Show all topics"""
    if request.user.is_authenticated:
        topics = Topic.objects.filter(Q(owner=request.user) | Q(public=True)).order_by(
            "date_added"
        )
    else:
        topics = Topic.objects.filter(public=True).order_by("date_added")

    context = {"topics": topics}
    return render(request, "learning_logs/topics.html", context)


def topic(request, topic_id):
    """Show a single topic and all its entries"""
    topic = get_object_or_404(Topic, id=topic_id)
    if not topic.public and (
        not request.user.is_authenticated or request.user != topic.owner
    ):
        raise Http404

    entries = topic.entry_set.order_by("-date_added")
    context = {"topic": topic, "entries": entries}
    return render(request, "learning_logs/topic.html", context)


@login_required
def new_topic(request):
    """Add a new topic"""
    if request.method != "POST":
        form = TopicForm()
    else:
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect("learning_logs:topics")

    context = {"form": form}
    return render(request, "learning_logs/new_topic.html", context)


@login_required
def new_entry(request, topic_id):
    """Add a new entry for a particular topic"""
    topic = get_object_or_404(Topic, id=topic_id)
    if topic.owner != request.user and not topic.public:
        raise Http404

    if request.method != "POST":
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.owner = request.user
            new_entry.save()
            return redirect("learning_logs:topic", topic_id=topic_id)

    context = {"topic": topic, "form": form}
    return render(request, "learning_logs/new_entry.html", context)


@login_required
def edit_entry(request, entry_id):
    """Edit an existing entry"""
    entry = get_object_or_404(Entry, id=entry_id)
    topic = entry.topic
    if entry.owner != request.user:
        raise Http404

    if request.method != "POST":
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("learning_logs:topic", topic_id=topic.id)

    context = {"entry": entry, "topic": topic, "form": form}
    return render(request, "learning_logs/edit_entry.html", context)

learning_log/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


def register(request):
    """Register a new user"""
    if request.method != "POST":
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect("learning_logs:index")

    context = {"form": form}
    return render(request, "registration/register.html", context)

learning_log/learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,
                         shrink-to-fit=no">
    <title>Learning log</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery="full" %}

</head>
<body>

    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">

        <a class="navbar-brand" href="{% url 'learning_logs:index' %}">Learning Log</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarCollapse" aria-controls="navbarCollapse"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'learning_logs:topics' %}">
                        Topics</a></li>
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Log in</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>
</body>
</html>

learning_log/learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <center>
    <h1><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h1>
    <h2>Edit entry:</h2>
    </center>
{% endblock page_header %}

{% block content %}
    <form method="post" action="{% url 'learning_logs:edit_entry' entry.id %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <center><button name="submit" class="btn btn-primary">
                    Save changes</button></center>
        {% endbuttons %}
    </form>

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
    <div class="jumbotron">
        <center><h1 class="display-3">Track your learning.<h1></center>

        <center>
            <p class="lead">Make your own Learning Log, and keep a list of the
                topics you're learning about. Or make a topic about something else.
                You can either keep your entries private or make it public, so
                anyone can read and comment.</p>
        </center>

        {% if not user.is_authenticated %}
            <center><a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
                            role="button">Register &raquo;</a></center>
        {% else %}
            <center><a class="btn btn-lg btn-primary" href="{% url 'learning_logs:topics' %}"
                            role="button">View topics &raquo;</a></center>
        {% endif %}
    </div>
{% endblock page_header %}

learning_log/learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <center>
    <h1><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h1>
    <h2>Add a new entry:</h2>
    </center>
{% endblock page_header %}

{% block content %}
    <form method="post" action="{% url 'learning_logs:new_entry' topic.id %}" clas="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <center><button name="submit" class="btn btn-primary">
                    Add entry</button></center>
        {% endbuttons %}
    </form>
{% endblock content %}

learning_log/learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <center><h1>Add a new topic</h1></center>
{% endblock page_header %}

{% block content %}

   <form method="post" action="{% url 'learning_logs:new_topic' %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <center><button name="submit" class="btn btn-primary">
                    Add topic</button></center>
        {% endbuttons %}
    </form>

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
    <center>
    <h1>{{ topic }}</h1>
    <h3><a href="{% url 'learning_logs:new_entry' topic.id %}">
            New entry</a></h3>
    </center>
{% endblock page_header %}

{% block content %}
    <p>
    </p>

    {% for entry in entries %}
        <div class="card mb-3">
            <h4 class="card-header">
                {{ entry.date_added|date:"H:i M d Y " }}{{ entry.owner }}
                {% if entry.owner == request.user %}
                    <small><a href="{% url 'learning_logs:edit_entry' entry.id %}">
                            Edit entry</a></small>
                {% endif %}
            </h4>
            <div class="card-body">
                {{ entry.text|linebreaks }}
            </div>
        </div>
    {% empty %}
        <p>There are no entries for this topic yet.</p>
    {% endfor %}
{% endblock content %}

learning_log/learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
    <center><h1>Topics</h1></center>
{% endblock page_header %}

{% block content %}
    <ul>
        {% for topic in topics %}
            <li><h3>
                <a href="{% url 'learning_logs:topic' topic.id %}">
                    {{ topic }}</a>
                {% if topic.public %}
                    <h5>Public</h5>
                {% else %}
                    <h5>Private</h5>
                {% endif %}
            </h3></li>
        {% empty %}
            <li><h3>No topics have been added yet.</h3></li>
        {% endfor %}
    </ul>

    <center><h3><a href="{% url 'learning_logs:new_topic' %}">
                Add a new topic</a></h3></center>
{% endblock content %}